# Numpy İşlemler

In [1]:
import numpy as np

In [2]:
a = np.array([20,40,60,80])

In [3]:
a

array([20, 40, 60, 80])

In [4]:
b = np.arange(4)

In [5]:
b

array([0, 1, 2, 3])

In [6]:
c = a+b

In [7]:
c

array([20, 41, 62, 83])

In [8]:
a += 1

In [9]:
a

array([21, 41, 61, 81])

In [10]:
a*b

array([  0,  41, 122, 243])

In [11]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [12]:
a>50

array([False, False,  True,  True])

In [15]:
x = np.random.randint(0,20,7)

In [16]:
x

array([15,  8, 17, 11, 18,  2, 10])

In [17]:
x.max()

18

In [18]:
x.min()

2

In [19]:
x.sum()

81

In [20]:
b = np.arange(15).reshape(3,5)

In [21]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [22]:
b.sum(axis=0)

array([15, 18, 21, 24, 27])

In [23]:
b.sum(axis=1)

array([10, 35, 60])

In [24]:
b.max(axis=1)

array([ 4,  9, 14])

In [26]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]], dtype=int32)

In [34]:
k = np.random.randint(0,10,10)

In [35]:
k

array([8, 0, 6, 0, 5, 2, 4, 4, 3, 6])

In [36]:
k.mean()

3.8

In [37]:
np.median(k)

4.0

In [38]:
np.std(k)

2.4819347291981715

In [39]:
np.var(k)

6.16

In [40]:
kopya = np.copy(k)

In [41]:
kopya

array([8, 0, 6, 0, 5, 2, 4, 4, 3, 6])

In [42]:
sehirler = np.array(["ankara","istanbul","izmir","adana","ankara","izmir","bursa","bursa"])

In [43]:
np.unique(sehirler)

array(['adana', 'ankara', 'bursa', 'istanbul', 'izmir'], dtype='<U8')