In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
np.ones((3,5))*7

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

In [8]:
b = np.arange(10,70,5)

In [9]:
b

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65])

In [10]:
c = np.linspace(0,5,15) 

In [11]:
c

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

In [13]:
d = np.random.randn(3,5)

In [14]:
d

array([[-0.6806647 ,  1.02770669,  0.9067585 , -0.05719316,  0.43290382],
       [ 0.8003701 , -1.08772305,  0.60830019,  0.66372806,  1.06794236],
       [-0.1990681 ,  0.14703294,  0.74480875,  0.23427095, -0.76363945]])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
e = np.arange(0,24)

In [44]:
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [45]:
e.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [28]:
f = np.random.rand(10)

In [29]:
f

array([0.00423313, 0.83035928, 0.39217409, 0.65237395, 0.56388954,
       0.87801687, 0.53196147, 0.9814096 , 0.24447743, 0.43725987])

In [30]:
f.max()

0.9814096000499102

In [31]:
f.min()

0.0042331347690023335

In [46]:
g = np.random.random(16).reshape(4,4)

In [47]:
g

array([[0.99692146, 0.18314648, 0.24341544, 0.27854027],
       [0.22361768, 0.78594011, 0.84548593, 0.9389813 ],
       [0.47082557, 0.38139058, 0.73729455, 0.21192022],
       [0.31704273, 0.64566445, 0.821299  , 0.81804226]])

In [48]:
g[1:2,:]

array([[0.22361768, 0.78594011, 0.84548593, 0.9389813 ]])

In [49]:
g[3,3]

0.8180422562596795

In [50]:
g[:,3:4]

array([[0.27854027],
       [0.9389813 ],
       [0.21192022],
       [0.81804226]])

In [52]:
for i in g.flat:
    print(i)

0.996921461725358
0.1831464763985141
0.24341544108004076
0.27854026984934976
0.22361767995540838
0.7859401101824065
0.8454859295645717
0.9389812957973727
0.47082556524559527
0.3813905824047412
0.7372945529150916
0.21192021944578654
0.3170427333121354
0.6456644489558488
0.8212989950683495
0.8180422562596795


In [53]:
h = np.random.random(4)*5

In [54]:
h

array([4.18269999, 3.3267234 , 2.48516151, 0.09911352])

In [55]:
h.sum()

10.09369841215067

In [56]:
np.std(h)

1.522927448641154

In [57]:
np.var(h)

2.3193080138246547

In [58]:
h.var() # aynı şey

2.3193080138246547