# Numpy Array Oluşturma

In [1]:
import numpy as np

In [5]:
x = np.array([22,548,44])

In [6]:
type(x)

numpy.ndarray

In [7]:
x

array([ 22, 548,  44])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones((4,5))*3

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [13]:
n = np.arange(10,65,5)

In [14]:
n

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [15]:
ondalık = np.arange(0,4,0.3)

In [16]:
ondalık

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3. , 3.3, 3.6,
       3.9])

In [20]:
lin = np.linspace(1,12,6)

In [21]:
lin

array([ 1. ,  3.2,  5.4,  7.6,  9.8, 12. ])

In [24]:
rast = np.random.rand(3,5)

In [25]:
rast

array([[0.4105295 , 0.51778303, 0.88080169, 0.12733343, 0.29206404],
       [0.53312724, 0.96675386, 0.1848775 , 0.1474238 , 0.13150872],
       [0.67316154, 0.43327526, 0.2558477 , 0.07515157, 0.19661   ]])

In [26]:
nygma = np.random.randn(2,4)

In [27]:
nygma

array([[ 0.72692498,  0.4824556 , -0.85849696,  1.13830191],
       [ 1.08355329,  0.35720887, -0.69840274,  0.05857273]])

In [28]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
tam = np.random.randint(1,50,9)

In [32]:
tam

array([40, 49, 19, 26, 19, 26, 16,  7, 43])

In [33]:
y = np.arange(24)

In [35]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [36]:
y.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [37]:
y.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [38]:
tam.max()

49

In [39]:
tam.min()

7

In [40]:
tam.argmin()

7

In [41]:
tam.argmax()

1

In [42]:
a = np.arange(50)
a.shape = 2,-1,5
a.shape

(2, 5, 5)

In [43]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])