# Numpy İndeksleme

In [1]:
import numpy as np

In [8]:
a = np.arange(10)

In [9]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
b = np.arange(10)**2

In [11]:
b

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [12]:
b[3]

9

In [13]:
b[3:6]

array([ 9, 16, 25], dtype=int32)

In [14]:
b[4]=15050

In [15]:
b

array([    0,     1,     4,     9, 15050,    25,    36,    49,    64,
          81], dtype=int32)

In [16]:
for i in b:
    print(i*2)

0
2
8
18
30100
50
72
98
128
162


# Çok Boyutlu Array

In [17]:
y = np.random.random(16)

In [18]:
y

array([0.8482651 , 0.13403081, 0.05735852, 0.17716569, 0.63285722,
       0.27812789, 0.86059099, 0.84001211, 0.04803834, 0.34632395,
       0.89967818, 0.27154132, 0.34190889, 0.91579868, 0.42811695,
       0.11224812])

In [19]:
y = y.reshape(4,4)

In [20]:
y

array([[0.8482651 , 0.13403081, 0.05735852, 0.17716569],
       [0.63285722, 0.27812789, 0.86059099, 0.84001211],
       [0.04803834, 0.34632395, 0.89967818, 0.27154132],
       [0.34190889, 0.91579868, 0.42811695, 0.11224812]])

In [21]:
y.ravel()

array([0.8482651 , 0.13403081, 0.05735852, 0.17716569, 0.63285722,
       0.27812789, 0.86059099, 0.84001211, 0.04803834, 0.34632395,
       0.89967818, 0.27154132, 0.34190889, 0.91579868, 0.42811695,
       0.11224812])

In [22]:
y[0:2,1]

array([0.13403081, 0.27812789])

In [23]:
y[:3,]

array([[0.8482651 , 0.13403081, 0.05735852, 0.17716569],
       [0.63285722, 0.27812789, 0.86059099, 0.84001211],
       [0.04803834, 0.34632395, 0.89967818, 0.27154132]])

In [24]:
for satır in y:
    print(satır)

[0.8482651  0.13403081 0.05735852 0.17716569]
[0.63285722 0.27812789 0.86059099 0.84001211]
[0.04803834 0.34632395 0.89967818 0.27154132]
[0.34190889 0.91579868 0.42811695 0.11224812]


In [25]:
for satır in y.flat:
    print(satır)

0.8482651035786787
0.13403080714644977
0.05735851993931418
0.17716569144129435
0.6328572194218676
0.2781278938784929
0.860590985454954
0.840012113882913
0.04803833928981838
0.34632395282395456
0.8996781753826115
0.2715413212811577
0.34190889380463874
0.9157986831305365
0.42811695272595973
0.11224812424825559


In [26]:
for satır in np.ndenumerate(y):
    print(satır)

((0, 0), 0.8482651035786787)
((0, 1), 0.13403080714644977)
((0, 2), 0.05735851993931418)
((0, 3), 0.17716569144129435)
((1, 0), 0.6328572194218676)
((1, 1), 0.2781278938784929)
((1, 2), 0.860590985454954)
((1, 3), 0.840012113882913)
((2, 0), 0.04803833928981838)
((2, 1), 0.34632395282395456)
((2, 2), 0.8996781753826115)
((2, 3), 0.2715413212811577)
((3, 0), 0.34190889380463874)
((3, 1), 0.9157986831305365)
((3, 2), 0.42811695272595973)
((3, 3), 0.11224812424825559)


In [27]:
c = np.array([1,2])
d = np.array([5,6])

In [28]:
np.hstack((c,d))

array([1, 2, 5, 6])

In [29]:
np.vstack((c,d))

array([[1, 2],
       [5, 6]])

In [45]:
c = np.array([[1,2],[3,4]])
d = np.array([[5,6],[7,8]])

In [46]:
np.concatenate((c,d),axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [47]:
np.concatenate((c,d.T), axis = 1)

array([[1, 2, 5, 7],
       [3, 4, 6, 8]])